# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS13-Text' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Texture/Core'
  # Pods for iOS13-Text

end
