# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PinFlexLayoutPlayground' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PinLayout'
  pod 'FlexLayout'
  # Pods for PinFlexLayoutPlayground

end
